plugins { id "com.android.application" }
android {
    namespace "io.github.liuanxin.scrollshot"
    compileSdk 36
    defaultConfig {
        applicationId "io.github.liuanxin.scrollshot"
        minSdk 34
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
        testInstrumentationRunner "io.github.liuanxin.scrollshot.ExportInstrumentation"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
dependencies { testImplementation "junit:junit:4.13.2" }
